### ISSUE TITLE
Error loading the page

### ISSUE THREAD

**Issue by mashish584** [netless-io/react-native-whiteboard#2]
I'm receiving an error while loading the WebView on iOS. In Android, "Joined" is logged in the terminal, but there is a white screen displayed.

![Simulator Screenshot - iPhone 15 Pro Max - 2023-10-28 at 23 07 52](https://github.com/netless-io/react-native-whiteboard/assets/33250693/419ce686-bba6-48d0-a8b1-b64a5daeeef2)

```
  <WhiteboardView
      sdkConfig={{
        appIdentifier: 'XXXXXX_X-XXX',
      }}
      roomConfig={{
        uid: 'ashish00584',
        uuid: roomData.roomUUID,
        roomToken: roomData.roomToken,
      }}
      joinRoomCallback={() => {
        console.log('Joined');
      }}
    />
```

**Comment by vince-hz** [comment]
Hi, I had just tried the example iOS project and it works without any error. Will this example work in your environment?

As for Android, a white screen means you create whiteboard success maybe. You can try touch on the screen. If it shows some colored lines, means it works.

**Comment by mashish584** [comment]
Hi Vince,
Thanks for taking a look. I'll try the example repository. I'll close the issue if it works.

**Comment by mashish584** [comment]
I tried to implement the example you guy's have posted in the repository. The issue I'm facing is related to 404 status on passed room Id.

**Error**
```
 {"__error":{"message":"connect failed: room \"364811e0773c11ee812c2d0de9c9ef6b\" not found","jsStack":"Error: connect failed: room \"364811e0773c11ee812c2d0de9c9ef6b\" not found\n    at a (file:///android_asset/Resource/web-sdk.5d487e2a.js:1:251051)\n    at e.value (file:///android_asset/Resource/web-sdk.5d487e2a.js:1:254007)\n    at Object.onDisconnect (file:///android_asset/Resource/web-sdk.5d487e2a.js:1:249194)\n    at i.value (file:///android_asset/Resource/web-sdk.5d487e2a.js:1:96280)\n    at o.onCloseByRemote (file:///android_asset/Resource/web-sdk.5d487e2a.js:1:91038)\n    at e.value (file:///android_asset/Resource/web-sdk.5d487e2a.js:1:88764)\n    at e.onReceivedPackage [as receiver] (file:///android_asset/Resource/web-sdk.5d487e2a.js:1:85949)\n    at WebSocket.onMessage (file:///android_asset/Resource/web-sdk.5d487e2a.js:1:83369)"}}
```

Below is the snippet of util I'm using to generate room UUID & also whiteboard component. I don't know what I'm doing wrong here.


**whiteboard.tsx**
```
import * as React from 'react';
import {Button, StyleSheet, View} from 'react-native';
import {
  WhiteboardView,
  Room,
  RoomPlayer,
  SDK,
  SDKConfig,
} from '@netless/react-native-whiteboard';

import {appIdentifier, getAgoraRoomDetails} from './utils';

let room: Room | undefined;
let roomPlayer: RoomPlayer | undefined;
let sdk: SDK | undefined;

const sdkParams: SDKConfig = {
  log: true,
  userCursor: true,
  appIdentifier,
  useMultiViews: true,
};

export default function App() {
  const [showRoom, setShowRoom] = React.useState<Boolean>(false);
  const [showPlayer, setShowPlayer] = React.useState<Boolean>(false);
  const [roomConfig, setRoomConfig] = React.useState({});

  const joinRoomCallback = React.useCallback((aRoom, aSdk, error) => {
    room = aRoom;
    sdk = aSdk;
    console.log({room, sdk});
    if (error) {
      console.log(error);
    }
  }, []);

  React.useEffect(() => {
    (async () => {
      const response = await getAgoraRoomDetails();
      const roomParams = {
        uuid: response.roomUUID,
        uid: 'ashish00584',
        roomToken: response.roomToken,
      };
      setRoomConfig(roomParams);
    })();
  }, []);

  return (
    <View style={styles.whiteboardContainer}>
      {!showRoom && (
        <View style={styles.buttonContainer}>
          <Button
            title="Live Room"
            onPress={() => setShowRoom(!showRoom)}></Button>
        </View>
      )}

      {showRoom && (
        <WhiteboardView
          style={styles.whiteboard}
          sdkConfig={sdkParams}
          roomConfig={roomConfig}
          joinRoomCallback={joinRoomCallback}
          // roomCallbacks={roomCallbacks}
          // sdkCallbacks={sdkCallbacks}
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  buttonContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  whiteboardContainer: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: 'black',
  },
  whiteboard: {
    aspectRatio: 16.0 / 9.0,
    flexGrow: 1,
  },
});

```

**util.ts**
```
import axios from 'axios';

const agoraAPI = 'https://api.netless.link/v5';
const agoraSDKToken ='NETLESSSDK_XXXX';

export const appIdentifier = 'xxxxxxx';

const api = axios.create({
  baseURL: agoraAPI,
  headers: {
    token: agoraSDKToken,
    region: 'in-mum',
  },
});

export interface RoomDetailsI {
  roomUUID: string;
  teamUUID: string;
  appUUID: string;
  roomToken: string;
}

export async function getAgoraRoomDetails(): Promise<RoomDetailsI> {
  const response = await api.post(`/rooms/`, {});

  const data = response.data;

  const roomInfo = await api.post(`/tokens/rooms/${data.uuid}/`, {
    lifespan: 3600000,
    role: 'admin',
  });

  return {
    roomUUID: data.uuid,
    teamUUID: data.teamUUID,
    appUUID: data.appUUID,
    roomToken: roomInfo.data,
  };
}
```

I'll appreciate your help.

Thanks

**Comment by vince-hz** [comment]
It seems you did not set the the region right in the react native code. Would you mind try set key value `region: 'in-mum'` for `roomParams`.

Please send your room uuid and room token to my email if you can not join room success after setting the region right. I will help you check the availability of the room. Here is my email: xuyunshi@agora.io

@mashish584

**Comment by mashish584** [comment]
Thanks @vince-hz . 

It's working on Android but on IOS I'm getting a warning mentioned below. 
```
Encountered an error loading page {"canGoBack": false, "canGoForward": false, "code": -1100, "description": "The requested URL was not found on this server.", "didFailProvisionalNavigation": true, "domain": "NSURLErrorDomain", "loading": false, "target": 25, "title": "", "url": ""}
``` 
Can this warning because I'm running in simulator? 

Also, I'm wondering is there is any way to have toolbox in whiteboard.

**Comment by vince-hz** [comment]
The warning comes from the web-view dependency. I will look into it tomorrow. If you want toolbox for whiteboard. Here is another repository with UI https://github.com/netless-io/react-native-fastboard.

**Comment by vince-hz** [comment]
I was running the example iOS code on my mac with Xcode 15.0 and simulator iPhone 15pro version 17.0. I did not see any warnings. And I had check the dependency `react-native-webview` version is 11.22.2.

**Comment by mashish584** [comment]
@vince-hz Thanks for all the support. It was a mistake from my end I did not run pod install. 

Closing this ticket.
